<?xml version = "1.0" ?>
<?xml-stylesheet type="text/xsl" href="MercurialSDR_BOM.xsl"?>
<!DOCTYPE GRID [
  <!ELEMENT GRID (BANDS, COLUMNS, ROWS*)>
  <!ATTLIST GRID ExportVersion CDATA #REQUIRED>
  <!ELEMENT BANDS (BAND*)>
  <!ELEMENT BAND EMPTY>
  <!ATTLIST BAND Index CDATA #REQUIRED>
  <!ATTLIST BAND Caption CDATA #IMPLIED>
  <!ELEMENT COLUMNS (COLUMN*)>
  <!ELEMENT COLUMN EMPTY>
  <!ATTLIST COLUMN Name CDATA #REQUIRED>
  <!ATTLIST COLUMN Caption CDATA #IMPLIED>
  <!ATTLIST COLUMN Index CDATA #REQUIRED>
  <!ATTLIST COLUMN BandIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN RowIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN ColIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN Width CDATA #IMPLIED>
  <!ELEMENT GROUP (GROUP*, ROW*)>
  <!ATTLIST GROUP GroupText CDATA #IMPLIED>
  <!ELEMENT ROWS (ROW*)>
  <!ELEMENT ROW EMPTY>
  <!ATTLIST ROW Part_Number CDATA #IMPLIED>
  <!ATTLIST ROW Designator CDATA #IMPLIED>
  <!ATTLIST ROW Comment CDATA #IMPLIED>
  <!ATTLIST ROW Description CDATA #IMPLIED>
  <!ATTLIST ROW Value CDATA #IMPLIED>
  <!ATTLIST ROW Material CDATA #IMPLIED>
  <!ATTLIST ROW Quantity CDATA #IMPLIED>
]>
<GRID ExportVersion="1.0">
  <BANDS>
    <BAND Index="0" Caption=""></BAND>
  </BANDS>
  <COLUMNS>
    <COLUMN Name="Part_Number" Caption="Part Number" Index="0" BandIndex="0" RowIndex="0" ColIndex="0" Width="144"></COLUMN>
    <COLUMN Name="Designator" Caption="Designator" Index="1" BandIndex="0" RowIndex="0" ColIndex="1" Width="101"></COLUMN>
    <COLUMN Name="Comment" Caption="Comment" Index="2" BandIndex="0" RowIndex="0" ColIndex="2" Width="146"></COLUMN>
    <COLUMN Name="Description" Caption="Description" Index="3" BandIndex="0" RowIndex="0" ColIndex="3" Width="154"></COLUMN>
    <COLUMN Name="Value" Caption="Value" Index="4" BandIndex="0" RowIndex="0" ColIndex="4" Width="67"></COLUMN>
    <COLUMN Name="Material" Caption="Material" Index="5" BandIndex="0" RowIndex="0" ColIndex="5" Width="100"></COLUMN>
    <COLUMN Name="Quantity" Caption="Quantity" Index="6" BandIndex="0" RowIndex="0" ColIndex="6" Width="69"></COLUMN>
  </COLUMNS>
  <ROWS>
    <ROW Part_Number="" Designator="JP1" Comment="Jumper" Description="Jumper 2x2" Value="" Material="" Quantity="1"></ROW>
    <ROW Part_Number="" Designator="JP2" Comment="Jumper" Description="Jumper" Value="" Material="" Quantity="1"></ROW>
    <ROW Part_Number="" Designator="TP1, TP3, TP4, TP6, TP7, TP9, TP10, TP11, TP12, TP13, TP15, TP16" Comment="Test Point" Description="Test Point" Value="" Material="" Quantity="12"></ROW>
    <ROW Part_Number="" Designator="TP2, TP5, TP14" Comment="Test Point" Description="Test Point" Value="" Material="" Quantity="3"></ROW>
    <ROW Part_Number="5-1814400-1" Designator="CN1, CN2, CN5" Comment="SMA" Description="Conector SMA" Value="" Material="" Quantity="3"></ROW>
    <ROW Part_Number="6-534236-2" Designator="CN3" Comment="Connector" Description="Conector gen&#233;rico 12x2" Value="" Material="" Quantity="1"></ROW>
    <ROW Part_Number="93LC56BT/SN" Designator="IC5" Comment="93LC56BT" Description="EEPROM SPI 2kb &#40;128x16&#41;" Value="" Material="" Quantity="1"></ROW>
    <ROW Part_Number="10118193-0001LF" Designator="CN4" Comment="micro-USB Plug" Description="USB Plug" Value="" Material="" Quantity="1"></ROW>
    <ROW Part_Number="AC0603FR-072K2L" Designator="R11" Comment="Resistor SMD" Description="Resistor" Value="2k2" Material="" Quantity="1"></ROW>
    <ROW Part_Number="AD5061BRJZ-2REEL7" Designator="IC1" Comment="Serial DAC" Description="DAC SPI" Value="" Material="" Quantity="1"></ROW>
    <ROW Part_Number="AP7217D-12YG-13" Designator="IC9" Comment="AP7217D" Description="Linear Voltage Regulator 1V2" Value="" Material="" Quantity="1"></ROW>
    <ROW Part_Number="AP7365-33YG-13" Designator="IC10" Comment="AP7215" Description="Linear Voltage Regulator 3v3" Value="" Material="" Quantity="1"></ROW>
    <ROW Part_Number="BC846BDW1T1G" Designator="IC6, IC7" Comment="BC846" Description="TBJ NPN Dual" Value="" Material="" Quantity="2"></ROW>
    <ROW Part_Number="BLM18AG121SN1D" Designator="FB1, FB2, FB3, FB4, FB5" Comment="Ferrite Bead" Description="Ferrite Bead" Value="" Material="" Quantity="5"></ROW>
    <ROW Part_Number="C1608X7S1A335K080AC" Designator="C27" Comment="Capacitor" Description="Capacitor no polarizado" Value="3.3uF" Material="Ceramic" Quantity="1"></ROW>
    <ROW Part_Number="CC0603KRX7R7BB103" Designator="C35" Comment="Capacitor" Description="Capacitor no polarizado" Value="10nF" Material="Ceramic" Quantity="1"></ROW>
    <ROW Part_Number="CL10A225KQ8NNNC" Designator="C8, C31, C32, C33, C34" Comment="Capacitor" Description="Capacitor no polarizado" Value="2.2uF" Material="Ceramic" Quantity="5"></ROW>
    <ROW Part_Number="CL10B104KO8NNNC" Designator="C1, C3, C4, C5, C6, C7, C9, C10, C11, C12, C13, C16, C17, C18, C19, C20, C22, C23, C25, C26, C30, C36, C42" Comment="Capacitor" Description="Capacitor no polarizado" Value="100nF" Material="Ceramic" Quantity="23"></ROW>
    <ROW Part_Number="CL10B105KP8NNNC" Designator="C38, C39, C40, C41" Comment="Capacitor" Description="Capacitor no polarizado" Value="1uF" Material="Ceramic" Quantity="4"></ROW>
    <ROW Part_Number="CL10C120JB8NNNC" Designator="C28, C29" Comment="Capacitor" Description="Capacitor no polarizado" Value="12pF" Material="Ceramic" Quantity="2"></ROW>
    <ROW Part_Number="CR0603-FX-1000ELF" Designator="R4, R5" Comment="Resistor SMD" Description="Resistor" Value="100" Material="" Quantity="2"></ROW>
    <ROW Part_Number="CR0603-FX-1001ELF" Designator="R9, R39, R41" Comment="Resistor SMD" Description="Resistor" Value="1k" Material="" Quantity="3"></ROW>
    <ROW Part_Number="CR0603-FX-1002EAS" Designator="R1, R2, R6, R7, R8, R12, R13, R14, R19, R26, R29, R32, R38, R40" Comment="Resistor SMD" Description="Resistor" Value="10k" Material="" Quantity="14"></ROW>
    <ROW Part_Number="CR0603-FX-1200ELF" Designator="R16, R17" Comment="Resistor SMD" Description="Resistor" Value="120" Material="" Quantity="2"></ROW>
    <ROW Part_Number="CR0603-FX-1202ELF" Designator="R10" Comment="Resistor SMD" Description="Resistor" Value="12k" Material="" Quantity="1"></ROW>
    <ROW Part_Number="CR0603-FX-1300ELF" Designator="R18, R20, R24, R25, R27, R28, R30, R31" Comment="Resistor SMD" Description="Resistor" Value="130" Material="" Quantity="8"></ROW>
    <ROW Part_Number="CR0603-FX-1500ELF" Designator="R34" Comment="Resistor SMD" Description="Resistor" Value="150" Material="" Quantity="1"></ROW>
    <ROW Part_Number="CR0603-FX-1800ELF" Designator="R15" Comment="Resistor SMD" Description="Resistor" Value="180" Material="" Quantity="1"></ROW>
    <ROW Part_Number="CR0603-FX-2612ELF" Designator="R21, R22, R23" Comment="Resistor SMD" Description="Resistor" Value="26.1k" Material="" Quantity="3"></ROW>
    <ROW Part_Number="CR0603-JW-331ELF" Designator="R33" Comment="Resistor SMD" Description="Resistor" Value="330" Material="" Quantity="1"></ROW>
    <ROW Part_Number="DSC6003JI2A-012.0000T" Designator="OSC1" Comment="Oscillator" Description="Oscilador de 4 terminales" Value="" Material="" Quantity="1"></ROW>
    <ROW Part_Number="ECS-120-12-33-AGN-TR" Designator="X1" Comment="XTAL_4term" Description="Oscilador a Cristal" Value="" Material="" Quantity="1"></ROW>
    <ROW Part_Number="FT2232HL-TRAY" Designator="IC4" Comment="FT2232H" Description="USB bridge" Value="" Material="" Quantity="1"></ROW>
    <ROW Part_Number="ICE40HX4K-TQ144" Designator="U1" Comment="iCE40HX4K-TQ144" Description="iCE40 HX4K Series FPGA Family, 3520 Logic Cells, 1.2 V Core, 80 K Embedded RAM Bits, 144-pin TQFP, Pb-Free, Tray" Value="" Material="" Quantity="1"></ROW>
    <ROW Part_Number="LE25U20AMB-AH" Designator="IC3" Comment="LE25U20AMB" Description="Flash Memmory SPI &#40;256Kx8&#41;" Value="" Material="" Quantity="1"></ROW>
    <ROW Part_Number="LTST-C190KRKT" Designator="D0, D1, D2, D3, D4, D5, D6, D7, D13" Comment="Led_small, Led_small, Led_small, Led_small, Led_small, Led_small, Led_small, Led_small, Led" Description="Led_small, Led_small, Led_small, Led_small, Led_small, Led_small, Led_small, Led_small, Led" Value="" Material="" Quantity="9"></ROW>
    <ROW Part_Number="LTST-C190KSKT" Designator="D9, D14" Comment="Led" Description="Led" Value="" Material="" Quantity="2"></ROW>
    <ROW Part_Number="LTST-G563EGBW" Designator="D11" Comment="RGB_LED" Description="Led RGB" Value="" Material="" Quantity="1"></ROW>
    <ROW Part_Number="MCP1541T-I/TT" Designator="IC8" Comment="Vref" Description="Reference Voltage" Value="" Material="" Quantity="1"></ROW>
    <ROW Part_Number="MCP6271T-E/OT" Designator="IC2" Comment="OPAMP" Description="Operational Amplifier" Value="" Material="" Quantity="1"></ROW>
    <ROW Part_Number="NSR0530HT1G" Designator="D10" Comment="Schottky Diode" Description="Diodo Schottkey" Value="" Material="" Quantity="1"></ROW>
    <ROW Part_Number="OPA356AIDBVR" Designator="IC11" Comment="OPAMP" Description="Operational Amplifier" Value="" Material="" Quantity="1"></ROW>
    <ROW Part_Number="PTS645SM43SMTR92 LFS" Designator="SW0, SW1, SW2, SW3, SW4" Comment="Pulsador" Description="Pulsador" Value="" Material="" Quantity="5"></ROW>
    <ROW Part_Number="RB521S30T1G" Designator="D8" Comment="Schottky Diode" Description="Diodo Schottkey" Value="" Material="" Quantity="1"></ROW>
    <ROW Part_Number="RC0603FR-07374RL" Designator="R36" Comment="Resistor SMD" Description="Resistor" Value="374" Material="" Quantity="1"></ROW>
    <ROW Part_Number="RC0603FR-07649RL" Designator="R3" Comment="Resistor SMD" Description="Resistor" Value="649" Material="" Quantity="1"></ROW>
    <ROW Part_Number="RC0603FR-07665RL" Designator="R35, R37" Comment="Resistor SMD" Description="Resistor" Value="665" Material="" Quantity="2"></ROW>
    <ROW Part_Number="SMAJ5.0A" Designator="D12" Comment="TVS Diode" Description="TVS &#40;Supresor de transitorios&#41;" Value="" Material="" Quantity="1"></ROW>
    <ROW Part_Number="TAJA106K006RNJ" Designator="C2, C14, C15, C37" Comment="Capacitor Polarizado" Description="Capacitor polarizado" Value="10uF" Material="Tantalum" Quantity="4"></ROW>
    <ROW Part_Number="TAJA475K010RNJ" Designator="C21, C24" Comment="Capacitor Polarizado" Description="Capacitor polarizado" Value="4.7uF" Material="Tantalum" Quantity="2"></ROW>
  </ROWS>
</GRID>
