<?xml version = "1.0" ?>
<?xml-stylesheet type="text/xsl" href="MercurialSDR.xsl"?>
<!DOCTYPE GRID [
  <!ELEMENT GRID (BANDS, COLUMNS, ROWS*)>
  <!ATTLIST GRID ExportVersion CDATA #REQUIRED>
  <!ELEMENT BANDS (BAND*)>
  <!ELEMENT BAND EMPTY>
  <!ATTLIST BAND Index CDATA #REQUIRED>
  <!ATTLIST BAND Caption CDATA #IMPLIED>
  <!ELEMENT COLUMNS (COLUMN*)>
  <!ELEMENT COLUMN EMPTY>
  <!ATTLIST COLUMN Name CDATA #REQUIRED>
  <!ATTLIST COLUMN Caption CDATA #IMPLIED>
  <!ATTLIST COLUMN Index CDATA #REQUIRED>
  <!ATTLIST COLUMN BandIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN RowIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN ColIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN Width CDATA #IMPLIED>
  <!ELEMENT GROUP (GROUP*, ROW*)>
  <!ATTLIST GROUP GroupText CDATA #IMPLIED>
  <!ELEMENT ROWS (ROW*)>
  <!ELEMENT ROW EMPTY>
  <!ATTLIST ROW Designator CDATA #IMPLIED>
  <!ATTLIST ROW Comment CDATA #IMPLIED>
  <!ATTLIST ROW Description CDATA #IMPLIED>
  <!ATTLIST ROW Part_Number CDATA #IMPLIED>
  <!ATTLIST ROW Value CDATA #IMPLIED>
  <!ATTLIST ROW Quantity CDATA #IMPLIED>
]>
<GRID ExportVersion="1.0">
  <BANDS>
    <BAND Index="0" Caption=""></BAND>
  </BANDS>
  <COLUMNS>
    <COLUMN Name="Designator" Caption="Designator" Index="0" BandIndex="0" RowIndex="0" ColIndex="0" Width="101"></COLUMN>
    <COLUMN Name="Comment" Caption="Comment" Index="1" BandIndex="0" RowIndex="0" ColIndex="1" Width="146"></COLUMN>
    <COLUMN Name="Description" Caption="Description" Index="2" BandIndex="0" RowIndex="0" ColIndex="2" Width="154"></COLUMN>
    <COLUMN Name="Part_Number" Caption="Part Number" Index="3" BandIndex="0" RowIndex="0" ColIndex="3" Width="144"></COLUMN>
    <COLUMN Name="Value" Caption="Value" Index="4" BandIndex="0" RowIndex="0" ColIndex="4" Width="67"></COLUMN>
    <COLUMN Name="Quantity" Caption="Quantity" Index="6" BandIndex="0" RowIndex="0" ColIndex="5" Width="69"></COLUMN>
  </COLUMNS>
  <ROWS>
    <ROW Designator="TP2, TP5, TP14" Comment="Test Point" Description="Test Point" Part_Number="" Value="" Quantity="3"></ROW>
    <ROW Designator="TP1, TP3, TP4, TP6, TP7, TP9, TP10, TP11, TP12, TP13, TP15, TP16" Comment="Test Point" Description="Test Point" Part_Number="" Value="" Quantity="12"></ROW>
    <ROW Designator="JP2" Comment="Jumper" Description="Jumper" Part_Number="" Value="" Quantity="1"></ROW>
    <ROW Designator="JP1" Comment="Jumper" Description="Jumper 2x2" Part_Number="" Value="" Quantity="1"></ROW>
    <ROW Designator="CN1, CN2" Comment="SMA" Description="Conector SMA" Part_Number="5-1814400-1" Value="" Quantity="2"></ROW>
    <ROW Designator="CN3" Comment="Connector" Description="Conector gen&#233;rico 12x2" Part_Number="6-534236-2" Value="" Quantity="1"></ROW>
    <ROW Designator="IC5" Comment="93LC56BT" Description="EEPROM SPI 2kb &#40;128x16&#41;" Part_Number="93LC56BT/SN" Value="" Quantity="1"></ROW>
    <ROW Designator="CN4" Comment="micro-USB Plug" Description="USB Plug" Part_Number="10118193-0001LF" Value="" Quantity="1"></ROW>
    <ROW Designator="R11" Comment="Resistor SMD" Description="Resistor" Part_Number="AC0603FR-072K2L" Value="2k2" Quantity="1"></ROW>
    <ROW Designator="IC1" Comment="Serial DAC" Description="DAC SPI" Part_Number="AD5061BRJZ-2REEL7" Value="" Quantity="1"></ROW>
    <ROW Designator="IC9" Comment="AP7217D" Description="Linear Voltage Regulator 1V2" Part_Number="AP7217D-12YG-13" Value="" Quantity="1"></ROW>
    <ROW Designator="IC10" Comment="AP7215" Description="Linear Voltage Regulator 3v3" Part_Number="AP7365-33YG-13" Value="" Quantity="1"></ROW>
    <ROW Designator="IC6, IC7" Comment="BC846" Description="TBJ NPN Dual" Part_Number="BC846BDW1T1G" Value="" Quantity="2"></ROW>
    <ROW Designator="FB1, FB2, FB3, FB4, FB5" Comment="Ferrite Bead" Description="Ferrite Bead" Part_Number="BLM18AG121SN1D" Value="" Quantity="5"></ROW>
    <ROW Designator="C27" Comment="Capacitor" Description="Capacitor no polarizado" Part_Number="C1608X7S1A335K080AC" Value="3.3uF" Quantity="1"></ROW>
    <ROW Designator="C35" Comment="Capacitor" Description="Capacitor no polarizado" Part_Number="CC0603KRX7R7BB103" Value="10nF" Quantity="1"></ROW>
    <ROW Designator="C8, C31, C32, C33, C34" Comment="Capacitor" Description="Capacitor no polarizado" Part_Number="CL10A225KQ8NNNC" Value="2.2uF" Quantity="5"></ROW>
    <ROW Designator="C1, C3, C4, C5, C6, C7, C9, C10, C11, C12, C13, C16, C17, C18, C19, C20, C22, C23, C25, C26, C30, C36, C42" Comment="Capacitor" Description="Capacitor no polarizado" Part_Number="CL10B104KO8NNNC" Value="100nF" Quantity="23"></ROW>
    <ROW Designator="C38, C39, C40, C41" Comment="Capacitor" Description="Capacitor no polarizado" Part_Number="CL10B105KP8NNNC" Value="1uF" Quantity="4"></ROW>
    <ROW Designator="C28, C29" Comment="Capacitor" Description="Capacitor no polarizado" Part_Number="CL10C120JB8NNNC" Value="12pF" Quantity="2"></ROW>
    <ROW Designator="R4, R5" Comment="Resistor SMD" Description="Resistor" Part_Number="CR0603-FX-1000ELF" Value="100" Quantity="2"></ROW>
    <ROW Designator="R9" Comment="Resistor SMD" Description="Resistor" Part_Number="CR0603-FX-1001ELF" Value="1k" Quantity="1"></ROW>
    <ROW Designator="R1, R2, R6, R7, R8, R12, R13, R14, R19, R26, R29, R32" Comment="Resistor SMD" Description="Resistor" Part_Number="CR0603-FX-1002EAS" Value="10k" Quantity="12"></ROW>
    <ROW Designator="R16, R17" Comment="Resistor SMD" Description="Resistor" Part_Number="CR0603-FX-1200ELF" Value="120" Quantity="2"></ROW>
    <ROW Designator="R10" Comment="Resistor SMD" Description="Resistor" Part_Number="CR0603-FX-1202ELF" Value="12k" Quantity="1"></ROW>
    <ROW Designator="R18, R20, R24, R25, R27, R28, R30, R31" Comment="Resistor SMD" Description="Resistor" Part_Number="CR0603-FX-1300ELF" Value="130" Quantity="8"></ROW>
    <ROW Designator="R15" Comment="Resistor SMD" Description="Resistor" Part_Number="CR0603-FX-1800ELF" Value="180" Quantity="1"></ROW>
    <ROW Designator="R21, R22, R23" Comment="Resistor SMD" Description="Resistor" Part_Number="CR0603-FX-2612ELF" Value="26.1k" Quantity="3"></ROW>
    <ROW Designator="R33" Comment="Resistor SMD" Description="Resistor" Part_Number="CR0603-JW-331ELF" Value="330" Quantity="1"></ROW>
    <ROW Designator="OSC1" Comment="Oscillator" Description="Oscilador de 4 terminales" Part_Number="DSC6003JI2A-012.0000T" Value="" Quantity="1"></ROW>
    <ROW Designator="X1" Comment="XTAL_4term" Description="Oscilador a Cristal" Part_Number="ECS-120-12-33-AGN-TR" Value="" Quantity="1"></ROW>
    <ROW Designator="R34" Comment="Resistor SMD" Description="Resistor" Part_Number="ERJ-3EKF1500V" Value="150" Quantity="1"></ROW>
    <ROW Designator="IC4" Comment="FT2232H" Description="USB bridge" Part_Number="FT2232HL-TRAY" Value="" Quantity="1"></ROW>
    <ROW Designator="U1" Comment="iCE40HX4K-TQ144" Description="iCE40 HX4K Series FPGA Family, 3520 Logic Cells, 1.2 V Core, 80 K Embedded RAM Bits, 144-pin TQFP, Pb-Free, Tray" Part_Number="ICE40HX4K-TQ144" Value="" Quantity="1"></ROW>
    <ROW Designator="IC3" Comment="LE25U20AMB" Description="Flash Memmory SPI &#40;256Kx8&#41;" Part_Number="LE25U20AMB-AH" Value="" Quantity="1"></ROW>
    <ROW Designator="D14" Comment="Led" Description="Led" Part_Number="LTST-C190KGKT" Value="" Quantity="1"></ROW>
    <ROW Designator="D0, D1, D2, D3, D4, D5, D6, D7, D13" Comment="Led_small, Led_small, Led_small, Led_small, Led_small, Led_small, Led_small, Led_small, Led" Description="Led_small, Led_small, Led_small, Led_small, Led_small, Led_small, Led_small, Led_small, Led" Part_Number="LTST-C190KRKT" Value="" Quantity="9"></ROW>
    <ROW Designator="D9" Comment="Led" Description="Led" Part_Number="LTST-C190KSKT" Value="" Quantity="1"></ROW>
    <ROW Designator="D11" Comment="RGB_LED" Description="Led RGB" Part_Number="LTST-G563EGBW" Value="" Quantity="1"></ROW>
    <ROW Designator="IC8" Comment="Vref" Description="Reference Voltage" Part_Number="MCP1541T-I/TT" Value="" Quantity="1"></ROW>
    <ROW Designator="IC2" Comment="OPAMP" Description="Operational Amplifier" Part_Number="MCP6271T-E/OT" Value="" Quantity="1"></ROW>
    <ROW Designator="D10" Comment="Schottky Diode" Description="Diodo Schottkey" Part_Number="NSR0530HT1G" Value="" Quantity="1"></ROW>
    <ROW Designator="IC11" Comment="OPAMP" Description="Operational Amplifier" Part_Number="OPA356AIDBVR" Value="" Quantity="1"></ROW>
    <ROW Designator="SW0, SW1, SW2, SW3, SW4" Comment="Pulsador" Description="Pulsador" Part_Number="PTS645SM43SMTR92 LFS" Value="" Quantity="5"></ROW>
    <ROW Designator="D8" Comment="Schottky Diode" Description="Diodo Schottkey" Part_Number="RB521S30T1G" Value="" Quantity="1"></ROW>
    <ROW Designator="R3" Comment="Resistor SMD" Description="Resistor" Part_Number="RC0603FR-07649RL" Value="649" Quantity="1"></ROW>
    <ROW Designator="D12" Comment="TVS Diode" Description="TVS &#40;Supresor de transitorios&#41;" Part_Number="SMAJ5.0A" Value="" Quantity="1"></ROW>
    <ROW Designator="C2, C14, C15, C37" Comment="Capacitor Polarizado" Description="Capacitor polarizado" Part_Number="TAJA106K006RNJ" Value="10uF" Quantity="4"></ROW>
    <ROW Designator="C21, C24" Comment="Capacitor Polarizado" Description="Capacitor polarizado" Part_Number="TAJA475K010RNJ" Value="4.7uF" Quantity="2"></ROW>
  </ROWS>
</GRID>
